name: Test and Build

#on:
#  pull_request:
#    branches: [master]
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Print version of Java and Maven
        run: |
          echo "Workflow executed."
          echo "JAVA version should print 21"
          java -version
          echo "Maven version should print 3.x.x"
          mvn -version

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          TAG=0.0.1
          echo "Latest tag is $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Increment version in POM
        id: increment_version
        run: |
          VERSION=${TAG#v}  # Remove the 'v' from the version tag (if it exists)
          IFS='.' read -r -a version_parts <<< "$VERSION"
          PATCH=${version_parts[2]}
          PATCH=$((PATCH + 1))  # Increment the patch version
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$PATCH"
          echo "New version will be $NEW_VERSION"

          # Update the version in the pom.xml
          mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Commit version bump
        run: |
          git config --global user.name "AkshataKadam"
          git config --global user.email "akshatakadam1908@gmail.com"
          git add pom.xml
          git commit -m "Auto-bump version to $NEW_VERSION"
          git push

      - name: Test and package
        run: mvn clean package test
