name: Test and Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4

        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        uses: actions/setup-maven@v3
        with:
          maven-version: 3.8.6
      - name: Build and Test
        run: mvn clean package test
